---
apiVersion: v1
kind: Service
metadata:
  name: flask-svc
  labels:
    app: flask-k8s-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: flask-k8s